warn = [
    "clippy::cargo",

    "clippy::nursery",
    "clippy::pedantic",
    "clippy::suspicious",

    "clippy::restriction",

    "clippy::missing_inline_in_public_items",
    "clippy::single_char_lifetime_names",
]


allow = [
    # REMOVE BEFORE RELEASE:
    "clippy::cargo_common_metadata",

    "clippy::shadow_reuse",
    "clippy::std_instead_of_alloc",
    "clippy::std_instead_of_core",
    "clippy::implicit_return",
    "clippy::missing_docs_in_private_items",
    "clippy::pub_use",
    "clippy::undocumented_safety_blocks",
]

# allow = [
#     "unsafe_code",

#     "clippy::multiple_crate_versions",

#     "clippy::needless_lifetimes",
#     "clippy::cast_possible_truncation",
#     "clippy::cast_precision_loss",
#     "clippy::cast_lossless",
#     "clippy::cast_sign_loss",

#     # Disable for release
#     "clippy::missing_safety_doc",
#     "clippy::missing_errors_doc",
#     "clippy::missing_panics_doc",
#     "clippy::cargo_common_metadata",

#     # Often worse for readability
#     "clippy::module_name_repetitions",
#     "clippy::option_if_let_else",
#     "clippy::similar_names",
# ]
